pretrained_model_path: ./checkpoints/dedede
output_dir: ./outputs/yurucamp_stamp
train_data:
  annotations_file: data/yurucamp_stamp/annotation.csv
  video_dir: data/yurucamp_stamp
  size: 512
  n_sample_frames: 8
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
  - anime 1girl speaking, white hair, blue eyes, masterpiece, best quality, 8k, detailed
    anime style
  - anime 1girl giving thumbs up
  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5
validation_steps: 50
trainable_modules:
- attn1.to_q
- attn1.to_k
- attn1.to_v
- attn2.to_q
- attn2.to_k
- attn2.to_v
- attn_temp
train_batch_size: 8
max_train_steps: 100000
learning_rate: 24e-05
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
gradient_accumulation_steps: 1
gradient_checkpointing: true
checkpointing_steps: 200
resume_from_checkpoint: null
mixed_precision: fp16
use_8bit_adam: false
enable_xformers_memory_efficient_attention: true
seed: 0
safe_serialization: true
