pretrained_model_path: "./checkpoints/dedede"
output_dir: "./outputs/yurucamp_stamp"

train_data:
  annotations_file: "data/yurucamp_stamp/annotation.csv"
  video_dir: "data/yurucamp_stamp"
  size: 512
  n_sample_frames: 8
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "anime 1girl speaking, white hair, blue eyes, masterpiece, best quality, 8k, detailed anime style"
    - "anime 1girl giving thumbs up"

  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5

learning_rate: 3e-5
train_batch_size: 8
max_train_steps: 100000
checkpointing_steps: 200
validation_steps: 50
trainable_modules:
  - "attn1.to_q"
  - "attn1.to_k"
  - "attn1.to_v"
  - "attn2.to_q"
  - "attn2.to_k"
  - "attn2.to_v"
  - "attn_temp"

seed: 0
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
