pretrained_model_path: "./checkpoints/dedede"
output_dir: "./outputs/tilting_head"

train_data:
  video_path: "data/tilting_head/tilting_head.mp4"
  prompt: "best quality, masterpiece, 8k, detailed anime style of 1girl"
  n_sample_frames: 8
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "masterpiece, best quality, 8k, detailed anime style of hatsune miku"

  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 600
checkpointing_steps: 1000
validation_steps: 200
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
