pretrained_model_path: "./checkpoints/dedede"
output_dir: "./outputs/yor_dedede_lr3e-5_seed33"

train_data:
  video_path: "data/yor.mp4"
  prompt: "anime 1girl speaking, black hair, red eyes, best quality, masterpiece, 8k, "
  n_sample_frames: 8
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "anime 1girl crying, black hair, red eyes, best quality, masterpiece, 8k"
    - "anime 1girl speaking, white hair, blue eyes, best quality, masterpiece, 8k"
    - "anime 1girl, crying, white hair, blue eyes, best quality, masterpiece, 8k"
    - "anime boy speaking, black hair, red eyes, best quality, masterpiece, 8k"
  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 7.5

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 600
checkpointing_steps: 1000
validation_steps: 200
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
